#!/bin/bash

if [ -z $1 ]
then
    read -p 'Enter the name of the project : ' projectName
else
    projectName=$1
fi


# Setting Up angular environment for the work
echo -e "\e[32m \nBEGINING \e[5mTHE PROJECT INSTALLTION...";


ng new $projectName --routing=false --style=scss -skip-test=true  #--dryRun=true 


if [ -d $projectName  ]
then
    cd $projectName;
else
    echo -e "\e[32m\nPROJECT NOT CREATED!!!!"
    exit
fi

                        #Automating angular project standart components, services

#getting flags
while getopts :l:a:s: option
do
case "${option}"
in
    l) lazy=${OPTARG};;
    a) auth=${OPTARG};;
    s) services=${OPTARG};;
esac
done

#setting up components and services
if [ auth = true ]
then
    echo -e "\e[32mCREATING AUTHENTICATION SERVICES AND COMPONENTS...\n"

    if [ lazy = true ]
    then
        ng g m auth --routing --module=app  #--dryRun=true
    fi
fi

 
if [ -n services ]
then
    for service in $services
    do 
        ng g s "services/${service}"  #--dryRun=true
    done
else
    echo -e "\e[32mNO SERVICES ${services} PROVIDED!!!"
fi

